# Stage 1: Build
FROM eclipse-temurin:8 AS build_image
WORKDIR /usr/src/app/
RUN apt-get update && apt-get install -y maven
COPY ./ /usr/src/app/
RUN mvn install -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:8
WORKDIR /usr/src/app/
COPY --from=build_image /usr/src/app/target/book-work-0.0.1-SNAPSHOT.jar ./book-work-0.0.1.jar

EXPOSE 9000
ENTRYPOINT ["java","-jar","book-work-0.0.1.jar"]

